### PR TITLE
Optionally export background layer, fix convert, restore layer transparency after export

### PR DESCRIPTION
**Pull request by Moini**
Hi @ray-hplus ,

Thanks for this fun piece of software!

I've edited the animation extension so that it will export a working gif file again, even with > 9 layers.
It also now has an option to export the background layer, and it automatically restores the layer transparencies after exporting, so the onion-skinning still works after first export.

I'd like to ask you about licencing, as I cannot find any licence info. Would you make this extension available for use/distribution with Inkscape by using GPLv2+ ?

If so, I can add the licence in for you ;-)

Also, I would like to ask you if you would like to upload your extension to inkscape.org, so more people can know about it. We've got an extension gallery at the website now: 
https://inkscape.org/en/download/addons/

Kind Regards,
 Moini

(Proof attached ;-) )

sheep

### CODE REVIEW

**Comment by ray-hplus** [comment]
Hey, thanks for the updates. Licence will be added soon.

**Comment by Moini** [comment]
Thank you, @ray-hplus ! :)

What do you think about uploading your extension to inkscape.org? 

We've got a gallery for extensions there, and currently, we are working on getting more people to upload theirs, to make them more well known and to have them available, in case of bitrot. A (very far away) goal would be to turn this into an 'app store' (without money) that can be accessed from inside the program.

As your extension fulfills a really often requested need, I think many people would be really happy to find it there. It's much more difficult to search the web, and find the right extension that works.

**Comment by ray-hplus** [comment]
I will be pleased to see my extension in such a list, because I love Inkscape a lot. 

What actions are required from me to get it there?  

And maybe you know for some conincidence... Are there any plans to migrate Inkscape itself to github? I think that would popularize it a little bit more among those who would like to contribute :)
And is there any work done on rendering optimization ? For my project I'm using blending in shapes and watching canvas updating itself step-by-step is a real pain. 

If I can help in any way - please, contact me.

As for my animation extension - I'll be happy to contribute it to community.

**Comment by Moini** [comment]
Great :)

So, these are the instructions for the current Inkscape website (it's being actively developed, and things may change (hopefully improve!) more or less often:

**These Items need to be prepared for upload:**

1. Zip file of the extension, including all necessary files (in this case, you can just use the github zip file). The current install directions can be found at the top of this page: https://inkscape.org/en/download/addons/ and guarantee that each user can get the files into the right place. Your extension additionally needs imagemagick installed, and it contains a subfolder, so a link to where to get imagemagick and a hint about what to do with the files would be helpful in the description.

2. A thumbnail. This should be a png or jpg and 190x190 in size. This will appear on the extensions page here: https://inkscape.org/en/download/addons/

**Howto:**
Step 1:
Goto https://inkscape.org and create an account if you don't already 
have one.

Step 2:
At the top of any page, you will see a link to "Upload Art or 
Resource". This link also appears on your user profile page in a side panel as 
"New Upload".

Step 3:
Clicking on either these will take you to an upload page where 
you can upload a zip file, thumbnail and text description and some tags.
Your description should say on which menu the extension is to be found.
Select the correct licence, add a link to the repo, and check 'published'. 
Use tags to indicate which build your extension works in. "0.91" for current build. "0.48" if it works in previous build also. "Windows", "Linux", "OS X" if you know it works on those (Works on Linux, don't know about the others). You can also add some more tags. The tags will currently not do a lot, but they will become more useful very soon.

Click Save.

Step 4: 
It would be helpful if, when the extension has been changed, you'd also update the uploaded file.
(as I know that I might forget this for my own extension, I added a sentence into the description that tells people to look into the repo to always get the most current version).




Github:
At the last hackfest in Leeds, Inkscape developers decided that, indeed, the project will move to github. There is no date for this yet, and as github doesn't seem to offer the bug management capacities launchpad has, bug reports will remain on launchpad... Also see: https://inkscape.org/en/news/2016/04/16/what-happened-hackfest-2016/

Rendering optimization:
Sorry, can't help with that question. As far as I know, the developers (I'm just one of the website people) are always trying to improve performance (and there's a real drop in performance in the current development version, due to a bugfix for something else, which needs to be fixed before the release of Inkscape 0.92), but it's a rather tedious, challenging, and not too fulfilling task, so I guess it's not easy to motivate someone to work on this. There has been a big improvement from 0.48 to 0.91, though. 

We'd be happy to have your help in any way you want to contribute. There's always a lot to do :) - from writing announcements or website contents, to website development, artwork, user help, translations, bug management to C++ development.

**Pull request merged**
